"""
LipidIMEA/lipids/_lmaps_classification.py

Dylan Ross (dylan.ross@pnnl.gov)

    dictionary including lipid class information, using Lipid MAPS classification system 
    https://www.lipidmaps.org/data/classification/LM_classification_exp.php

    additional properties (other_props): ContainsEther, ContainsDiether, ContainsPlasmalogen, ContainsLCB, 
        ContainsLCB+OH, ContainsLCB-OH, IsOxoCHO, IsOxoCOOH, NumOH, ContainsOOH, ContainsF2IsoP

    TODO: (Dylan Ross) Add a helper function to add new lipid class rules
"""


LMAPS_CLASSIFICATION = {
    'Fatty Acyls': {
        'Fatty Acids and Conjugates': {
            'Straight chain fatty acids': {
                'lm_id_prefix': 'LMFA0101',
                'class_abbrev': 'FA',
                'fa_mod': '',
                'formula' : {
                    'C': lambda c: c,
                    'H': lambda c, u: 2 * c,
                    'N': 0,
                    'O': 2,
                    'S': 0,
                    'P': 0,
                },
                'ionization' : 'neg',
                'n_chains': 1,
                'other_props': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
            },
            'Unsaturated fatty acids': {
                'lm_id_prefix': 'LMFA0103',
                'class_abbrev': 'FA',
                'fa_mod': '',
                'formula' : {
                    'C': lambda c: c,
                    'H': lambda c, u: 2 * (c - u),
                    'N': 0,
                    'O': 2,
                    'S': 0,
                    'P': 0,
                },
                'ionization' : 'neg',
                'n_chains': 1,
                'other_props': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
            },
        },
        'Fatty esters': {
            'Fatty acyl carnitines': {
                'lm_id_prefix': 'LMFA0707',
                'class_abbrev': 'CAR',
                'fa_mod': '',
                'formula' : {
                    'C': lambda c: c + 7,
                    'H': lambda c, u: 2 * c + 13 - 2 * u,
                    'N': 1,
                    'O': 4,
                    'S': 0,
                    'P': 0,
                },
                'ionization' : 'pos',
                'n_chains': 1,
                'other_props': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
            },
        },
    },
    'Glycerolipids': {
        'Monoradylglycerols': {
            'Monoacylglycerols': {
                'lm_id_prefix': 'LMGL0101',
                'class_abbrev': 'MG',
                'fa_mod': '',
                'formula' : {
                    'C': lambda c: c + 3,
                    'H': lambda c, u: 2 * (c + 3 - u),
                    'N': 0,
                    'O': 4,
                    'S': 0,
                    'P': 0,
                },
                'ionization' : 'pos',
                'n_chains': 1,
                'other_props': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
            },
        },
        'Diradylglycerols': {
            'Diacylglycerols': {
                'lm_id_prefix': 'LMGL0201',
                'class_abbrev': 'DG',
                'fa_mod': '',
                'formula' : {
                    'C': lambda c: c + 3,
                    'H': lambda c, u: 2 * (c + 2 - u),
                    'N': 0,
                    'O': 5,
                    'S': 0,
                    'P': 0,
                },
                'ionization' : 'pos',
                'n_chains': 2,
                'other_props': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
            },
        },
        'Triradylglycerols': {
            'Triacylglycerols': {
                'lm_id_prefix': 'LMGL0301',
                'class_abbrev': 'TG',
                'fa_mod': '',
                'formula' : {
                    'C': lambda c: c + 3,
                    'H': lambda c, u: 2 * (c + 1 - u),
                    'N': 0,
                    'O': 6,
                    'S': 0,
                    'P': 0,
                },
                'ionization' : 'pos',
                'n_chains': 3,
                'other_props': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
            },
        },
        'Glycosyldiradylglycerols': {
            'Glycosyldiacylglycerols': [
                {
                    'lm_id_prefix': 'LMGL0501',
                    'class_abbrev': 'MGDG',
                    'fa_mod': '',
                    'formula' : {
                        'C': lambda c: c + 9,
                        'H': lambda c, u: 2 * (c + 7 - u),
                        'N': 0,
                        'O': 10,
                        'S': 0,
                        'P': 0,
                    },
                    'ionization' : 'pos',
                    'n_chains': 2,
                    'other_props': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                },
                {
                    'lm_id_prefix': 'LMGL0501',
                    'class_abbrev': 'DGDG',
                    'fa_mod': '',
                    'formula' : {
                        'C': lambda c: c + 15,
                        'H': lambda c, u: 2 * (c + 12 - u),
                        'N': 0,
                        'O': 15,
                        'S': 0,
                        'P': 0,
                    },
                    'ionization' : 'pos',
                    'n_chains': 2,
                    'other_props': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                },
                {
                    'lm_id_prefix': 'LMGL0501',
                    'class_abbrev': 'SQDG',
                    'fa_mod': '',
                    'formula' : {
                        'C': lambda c: c + 9,
                        'H': lambda c, u: 2 * (c + 7 - u),
                        'N': 0,
                        'O': 12,
                        'S': 1,
                        'P': 0,
                    },
                    'ionization' : 'pos',
                    'n_chains': 2,
                    'other_props': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                },
            ],
        },
    },
    'Glycerophospholipids': {
        'Glycerophosphocholines': {
            # ---------- PCs ----------
            'Diacylglycerophosphocholines': {
                'lm_id_prefix': 'LMGP0101',
                'class_abbrev': 'PC',
                'fa_mod': '',
                'formula' : {
                    'C': lambda c: c + 8,
                    'H': lambda c, u: 2 * (c + 8 - u),
                    'N': 1,
                    'O': 8,
                    'S': 0,
                    'P': 1,
                },
                'ionization' : 'pos',
                'n_chains': 2,
                'other_props': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
            },
            '1-alkyl,2-acylglycerophosphocholines': {
                'lm_id_prefix': 'LMGP0102',
                'class_abbrev': 'PC',
                'fa_mod': 'O-',
                'formula' : {
                    'C': lambda c: c + 8,
                    'H': lambda c, u: 2 * (c + 9 - u),
                    'N': 1,
                    'O': 7,
                    'S': 0,
                    'P': 1,
                },
                'ionization' : 'pos',
                'n_chains': 2,
                'other_props': [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
            },
            '1-(1Z-alkenyl),2-acylglycerophosphocholines': {
                'lm_id_prefix': 'LMGP0103',
                'class_abbrev': 'PC',
                'fa_mod': 'P-',
                'formula' : {
                    'C': lambda c: c + 8,
                    'H': lambda c, u: 2 * (c + 8 - u),
                    'N': 1,
                    'O': 7,
                    'S': 0,
                    'P': 1,
                },
                'ionization' : 'pos',
                'n_chains': 2,
                'other_props': [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
            },
            'Monoacylglycerophosphocholines': {
                'lm_id_prefix': 'LMGP0105',
                'class_abbrev': 'PC',
                'fa_mod': '',
                'formula' : {
                    'C': lambda c: c + 8,
                    'H': lambda c, u: 2 * (c + 9 - u),
                    'N': 1,
                    'O': 7,
                    'S': 0,
                    'P': 1,
                },
                'ionization' : 'pos',
                'n_chains': 1,
                'other_props': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
            },
            'Monoalkylglycerophosphocholines': {
                'lm_id_prefix': 'LMGP0106',
                'class_abbrev': 'PC',
                'fa_mod': 'O-',
                'formula' : {
                    'C': lambda c: c + 8,
                    'H': lambda c, u: 2 * (c + 10 - u),
                    'N': 1,
                    'O': 6,
                    'S': 0,
                    'P': 1,
                },
                'ionization' : 'pos',
                'n_chains': 1,
                'other_props': [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
            },
            '1Z-alkenylglycerophosphocholines': {
                'lm_id_prefix': 'LMGP0107',
                'class_abbrev': 'PC',
                'fa_mod': 'P-',
                'formula' : {
                    'C': lambda c: c + 8,
                    'H': lambda c, u: 2 * (c + 9 - u),
                    'N': 1,
                    'O': 6,
                    'S': 0,
                    'P': 1,
                },
                'ionization' : 'pos',
                'n_chains': 1,
                'other_props': [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
            },
        },
        # ---------- PEs ----------
        'Glycerophosphoethanolamines': {
            'Diacylglycerophosphoethanolamines': {
                'lm_id_prefix': 'LMGP0201',
                'class_abbrev': 'PE',
                'fa_mod': '',
                'formula' : {
                    'C': lambda c: c + 5,
                    'H': lambda c, u: 2 * (c + 5 - u),
                    'N': 1,
                    'O': 8,
                    'S': 0,
                    'P': 1,
                },
                'ionization' : 'both',
                'n_chains': 2,
                'other_props': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
            },
            '1-alkyl,2-acylglycerophosphoethanolamines': {
                'lm_id_prefix': 'LMGP0202',
                'class_abbrev': 'PE',
                'fa_mod': 'O-',
                'formula' : {
                    'C': lambda c: c + 5,
                    'H': lambda c, u: 2 * (c + 6 - u),
                    'N': 1,
                    'O': 7,
                    'S': 0,
                    'P': 1,
                },
                'ionization' : 'both',
                'n_chains': 2,
                'other_props': [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
            },
            '1-(1Z-alkenyl),2-acylglycerophosphoethanolamines': {
                'lm_id_prefix': 'LMGP0203',
                'class_abbrev': 'PE',
                'fa_mod': 'P-',
                'formula' : {
                    'C': lambda c: c + 5,
                    'H': lambda c, u: 2 * (c + 5 - u),
                    'N': 1,
                    'O': 7,
                    'S': 0,
                    'P': 1,
                },
                'ionization' : 'both',
                'n_chains': 2,
                'other_props': [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
            },
            'Monoacylglycerophosphoethanolamines': {
                'lm_id_prefix': 'LMGP0205',
                'class_abbrev': 'PE',
                'fa_mod': '',
                'formula' : {
                    'C': lambda c: c + 5,
                    'H': lambda c, u: 2 * (c + 6 - u),
                    'N': 1,
                    'O': 7,
                    'S': 0,
                    'P': 1,
                },
                'ionization' : 'both',
                'n_chains': 1,
                'other_props': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
            },
            'Monoalkylglycerophosphoethanolamines': {
                'lm_id_prefix': 'LMGP0206',
                'class_abbrev': 'PE',
                'fa_mod': 'O-',
                'formula' : {
                    'C': lambda c: c + 5,
                    'H': lambda c, u: 2 * (c + 7 - u),
                    'N': 1,
                    'O': 6,
                    'S': 0,
                    'P': 1,
                },
                'ionization' : 'both',
                'n_chains': 1,
                'other_props': [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
            },
            '1Z-alkenylglycerophosphoethanolamines': {
                'lm_id_prefix': 'LMGP0207',
                'class_abbrev': 'PE',
                'fa_mod': 'P-',
                'formula' : {
                    'C': lambda c: c + 5,
                    'H': lambda c, u: 2 * (c + 6 - u),
                    'N': 1,
                    'O': 6,
                    'S': 0,
                    'P': 1,
                },
                'ionization' : 'both',
                'n_chains': 1,
                'other_props': [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
            },
        },
        # ---------- PSs ----------
        'Glycerophosphoserines': {
            'Diacylglycerophosphoserines': {
                'lm_id_prefix': 'LMGP0301',
                'class_abbrev': 'PS',
                'fa_mod': '',
                'formula' : {
                    'C': lambda c: c + 6,
                    'H': lambda c, u: 2 * (c + 5 - u),
                    'N': 1,
                    'O': 10,
                    'S': 0,
                    'P': 1,
                },
                'ionization' : 'both',
                'n_chains': 2,
                'other_props': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
            },
            '1-alkyl,2-acylglycerophosphoserines': {
                'lm_id_prefix': 'LMGP0302',
                'class_abbrev': 'PS',
                'fa_mod': 'O-',
                'formula' : {
                    'C': lambda c: c + 6,
                    'H': lambda c, u: 2 * (c + 6 - u),
                    'N': 1,
                    'O': 9,
                    'S': 0,
                    'P': 1,
                },
                'ionization' : 'both',
                'n_chains': 2,
                'other_props': [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
            },
            '1-(1Z-alkenyl),2-acylglycerophosphoserines': {
                'lm_id_prefix': 'LMGP0303',
                'class_abbrev': 'PS',
                'fa_mod': 'P-',
                'formula' : {
                    'C': lambda c: c + 6,
                    'H': lambda c, u: 2 * (c + 5 - u),
                    'N': 1,
                    'O': 9,
                    'S': 0,
                    'P': 1,
                },
                'ionization' : 'both',
                'n_chains': 2,
                'other_props': [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
            },
            'Monoacylglycerophosphoserines': {
                'lm_id_prefix': 'LMGP0305',
                'class_abbrev': 'PS',
                'fa_mod': '',
                'formula' : {
                    'C': lambda c: c + 6,
                    'H': lambda c, u: 2 * (c + 6 - u),
                    'N': 1,
                    'O': 8,
                    'S': 0,
                    'P': 1,
                },
                'ionization' : 'both',
                'n_chains': 1,
                'other_props': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
            },
            'Monoalkylglycerophosphoserines': {
                'lm_id_prefix': 'LMGP0306',
                'class_abbrev': 'PS',
                'fa_mod': 'O-',
                'formula' : {
                    'C': lambda c: c + 6,
                    'H': lambda c, u: 2 * (c + 6 - u),
                    'N': 1,
                    'O': 8,
                    'S': 0,
                    'P': 1,
                },
                'ionization' : 'both',
                'n_chains': 1,
                'other_props': [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
            },
            '1Z-alkenylglycerophosphoserines': {
                'lm_id_prefix': 'LMGP0307',
                'class_abbrev': 'PS',
                'fa_mod': 'P-',
                'formula' : {
                    'C': lambda c: c + 6,
                    'H': lambda c, u: 2 * (c + 5 - u),
                    'N': 1,
                    'O': 9,
                    'S': 0,
                    'P': 1,
                },
                'ionization' : 'both',
                'n_chains': 1,
                'other_props': [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
            },
        },
        # ---------- PGs ----------
        'Glycerophosphoglycerols': {
            'Diacylglycerophosphoglycerols': {
                'lm_id_prefix': 'LMGP0401',
                'class_abbrev': 'PG',
                'fa_mod': '',
                'formula' : {
                    'C': lambda c: c + 6,
                    'H': lambda c, u: 2 * c + 11 - 2 * u,
                    'N': 0,
                    'O': 10,
                    'S': 0,
                    'P': 1,
                },
                'ionization' : 'neg',
                'n_chains': 2,
                'other_props': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
            },
            '1-alkyl,2-acylglycerophosphoglycerols': {
                'lm_id_prefix': 'LMGP0402',
                'class_abbrev': 'PG',
                'fa_mod': 'O-',
                'formula' : {
                    'C': lambda c: c + 6,
                    'H': lambda c, u: 2 * c + 13 - 2 * u,
                    'N': 0,
                    'O': 9,
                    'S': 0,
                    'P': 1,
                },
                'ionization' : 'neg',
                'n_chains': 2,
                'other_props': [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
            },
            '1-(1Z-alkenyl),2-acylglycerophosphoglycerols': {
                'lm_id_prefix': 'LMGP0403',
                'class_abbrev': 'PG',
                'fa_mod': 'P-',
                'formula' : {
                    'C': lambda c: c + 6,
                    'H': lambda c, u: 2 * c + 11 - 2 * u,
                    'N': 0,
                    'O': 9,
                    'S': 0,
                    'P': 1,
                },
                'ionization' : 'neg',
                'n_chains': 2,
                'other_props': [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
            },
            'Monoacylglycerophosphoglycerols': {
                'lm_id_prefix': 'LMGP0405',
                'class_abbrev': 'PG',
                'fa_mod': '',
                'formula' : {
                    'C': lambda c: c + 6,
                    'H': lambda c, u: 2 * c + 13 - 2 * u,
                    'N': 0,
                    'O': 9,
                    'S': 0,
                    'P': 1,
                },
                'ionization' : 'neg',
                'n_chains': 1,
                'other_props': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
            },
            'Monoalkylglycerophosphoglycerols': {
                'lm_id_prefix': 'LMGP0406',
                'class_abbrev': 'PG',
                'fa_mod': 'O-',
                'formula' : {
                    'C': lambda c: c + 6,
                    'H': lambda c, u: 2 * c + 15 - 2 * u,
                    'N': 0,
                    'O': 8,
                    'S': 0,
                    'P': 1,
                },
                'ionization' : 'neg',
                'n_chains': 1,
                'other_props': [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
            },
            '1Z-alkenylglycerophosphoglycerols': {
                'lm_id_prefix': 'LMGP0407',
                'class_abbrev': 'PG',
                'fa_mod': 'P-',
                'formula' : {
                    'C': lambda c: c + 6,
                    'H': lambda c, u: 2 * c + 13 - 2 * u,
                    'N': 0,
                    'O': 8,
                    'S': 0,
                    'P': 1,
                },
                'ionization' : 'neg',
                'n_chains': 1,
                'other_props': [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
            },
        },
        # ---------- PIs ----------
        'Glycerophosphoinositols': {
            'Diacylglycerophosphoinositols': {
                'lm_id_prefix': 'LMGP0601',
                'class_abbrev': 'PI',
                'fa_mod': '',
                'formula' : {
                    'C': lambda c: c + 9,
                    'H': lambda c, u: 2 * c + 15 - 2 * u,
                    'N': 0,
                    'O': 13,
                    'S': 0,
                    'P': 1,
                },
                'ionization' : 'neg',
                'n_chains': 2,
                'other_props': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
            },
            '1-alkyl,2-acylglycerophosphoinositols': {
                'lm_id_prefix': 'LMGP0602',
                'class_abbrev': 'PI',
                'fa_mod': 'O-',
                'formula' : {
                    'C': lambda c: c + 9,
                    'H': lambda c, u: 2 * c + 17 - 2 * u,
                    'N': 0,
                    'O': 12,
                    'S': 0,
                    'P': 1,
                },
                'ionization' : 'neg',
                'n_chains': 2,
                'other_props': [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
            },
            '1-(1Z-alkenyl),2-acylglycerophosphoinositols': {
                'lm_id_prefix': 'LMGP0603',
                'class_abbrev': 'PI',
                'fa_mod': 'P-',
                'formula' : {
                    'C': lambda c: c + 9,
                    'H': lambda c, u: 2 * c + 15 - 2 * u,
                    'N': 0,
                    'O': 12,
                    'S': 0,
                    'P': 1,
                },
                'ionization' : 'neg',
                'n_chains': 2,
                'other_props': [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
            },
            'Monoacylglycerophosphoinositols': {
                'lm_id_prefix': 'LMGP0605',
                'class_abbrev': 'PI',
                'fa_mod': '',
                'formula' : {
                    'C': lambda c: c + 9,
                    'H': lambda c, u: 2 * c + 17 - 2 * u,
                    'N': 0,
                    'O': 12,
                    'S': 0,
                    'P': 1,
                },
                'ionization' : 'neg',
                'n_chains': 1,
                'other_props': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
            },
            'Monoalkylglycerophosphoinositols': {
                'lm_id_prefix': 'LMGP0606',
                'class_abbrev': 'PI',
                'fa_mod': 'O-',
                'formula' : {
                    'C': lambda c: c + 9,
                    'H': lambda c, u: 2 * c + 19 - 2 * u,
                    'N': 0,
                    'O': 11,
                    'S': 0,
                    'P': 1,
                },
                'ionization' : 'neg',
                'n_chains': 1,
                'other_props': [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
            },
            '1Z-alkenylglycerophosphoinositols': {
                'lm_id_prefix': 'LMGP0607',
                'class_abbrev': 'PI',
                'fa_mod': 'P-',
                'formula' : {
                    'C': lambda c: c + 9,
                    'H': lambda c, u: 2 * c + 17 - 2 * u,
                    'N': 0,
                    'O': 11,
                    'S': 0,
                    'P': 1,
                },
                'ionization' : 'neg',
                'n_chains': 1,
                'other_props': [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
            },
        },
        # ---------- PIPs ----------
        'Glycerophosphoinositol monophosphates': {
            'Diacylglycerophosphoinositol monophosphates': {
                'lm_id_prefix': 'LMGP0701',
                'class_abbrev': 'PIP',
                'fa_mod': '',
                'formula' : {
                    'C': lambda c: c + 9,
                    'H': lambda c, u: 2 * (c + 8 - u),
                    'N': 0,
                    'O': 16,
                    'S': 0,
                    'P': 2,
                },
                'ionization' : 'neg',
                'n_chains': 2,
                'other_props': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
            },
            'Monoacylglycerophosphoinositol monophosphates': {
                'lm_id_prefix': 'LMGP0705',
                'class_abbrev': 'PIP',
                'fa_mod': '',
                'formula' : {
                    'C': lambda c: c + 9,
                    'H': lambda c, u: 2 * (c + 9 - u),
                    'N': 0,
                    'O': 15,
                    'S': 0,
                    'P': 2,
                },
                'ionization' : 'neg',
                'n_chains': 1,
                'other_props': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
            },
        },
        # ---------- PIP2s ----------
        'Glycerophosphoinositol bisphosphates': {
            'Diacylglycerophosphoinositol bisphosphates': {
                'lm_id_prefix': 'LMGP0801',
                'class_abbrev': 'PIP2',
                'fa_mod': '',
                'formula' : {
                    'C': lambda c: c + 9,
                    'H': lambda c, u: 2 * c + 17 - 2 * u,
                    'N': 0,
                    'O': 19,
                    'S': 0,
                    'P': 3,
                },
                'ionization' : 'neg',
                'n_chains': 2,
                'other_props': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
            },
        },
        # ---------- PIP3s ----------
        'Glycerophosphoinositol trisphosphates': {
            'Diacylglycerophosphoinositol trisphosphates': {
                'lm_id_prefix': 'LMGP0901',
                'class_abbrev': 'PIP3',
                'fa_mod': '',
                'formula' : {
                    'C': lambda c: c + 9,
                    'H': lambda c, u: 2 * c + 18 - 2 * u,
                    'N': 0,
                    'O': 22,
                    'S': 0,
                    'P': 4,
                },
                'ionization' : 'neg',
                'n_chains': 2,
                'other_props': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
            },
        },
        # ---------- PAs ----------
        'Glycerophosphates': {
            'Diacylglycerophosphates': {
                'lm_id_prefix': 'LMGP1001',
                'class_abbrev': 'PA',
                'fa_mod': '',
                'formula' : {
                    'C': lambda c: c + 3,
                    'H': lambda c, u: 2 * c + 5 - 2 * u,
                    'N': 0,
                    'O': 8,
                    'S': 0,
                    'P': 1,
                },
                'ionization' : 'neg',
                'n_chains': 2,
                'other_props': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
            },
            '1-alkyl,2-acylglycerophosphates': {
                'lm_id_prefix': 'LMGP1002',
                'class_abbrev': 'PA',
                'fa_mod': 'O-',
                'formula' : {
                    'C': lambda c: c + 3,
                    'H': lambda c, u: 2 * c + 7 - 2 * u,
                    'N': 0,
                    'O': 7,
                    'S': 0,
                    'P': 1,
                },
                'ionization' : 'neg',
                'n_chains': 2,
                'other_props': [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
            },
            '1-(1Z-alkenyl),2-acylglycerophosphates': {
                'lm_id_prefix': 'LMGP1003',
                'class_abbrev': 'PA',
                'fa_mod': 'P-',
                'formula' : {
                    'C': lambda c: c + 3,
                    'H': lambda c, u: 2 * c + 5 - 2 * u,
                    'N': 0,
                    'O': 7,
                    'S': 0,
                    'P': 1,
                },
                'ionization' : 'neg',
                'n_chains': 2,
                'other_props': [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
            },
            'Monoacylglycerophosphates': {
                'lm_id_prefix': 'LMGP1005',
                'class_abbrev': 'PA',
                'fa_mod': '',
                'formula' : {
                    'C': lambda c: c + 3,
                    'H': lambda c, u: 2 * c + 7 - 2 * u,
                    'N': 0,
                    'O': 7,
                    'S': 0,
                    'P': 1,
                },
                'ionization' : 'neg',
                'n_chains': 1,
                'other_props': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
            },
            'Monoalkylglycerophosphates': {
                'lm_id_prefix': 'LMGP1006',
                'class_abbrev': 'PA',
                'fa_mod': 'O-',
                'formula' : {
                    'C': lambda c: c + 3,
                    'H': lambda c, u: 2 * c + 9 - 2 * u,
                    'N': 0,
                    'O': 6,
                    'S': 0,
                    'P': 1,
                },
                'ionization' : 'neg',
                'n_chains': 1,
                'other_props': [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
            },
            '1Z-alkenylglycerophosphates': {
                'lm_id_prefix': 'LMGP1007',
                'class_abbrev': 'PA',
                'fa_mod': 'P-',
                'formula' : {
                    'C': lambda c: c + 3,
                    'H': lambda c, u: 2 * c + 7 - 2 * u,
                    'N': 0,
                    'O': 6,
                    'S': 0,
                    'P': 1,
                },
                'ionization' : 'neg',
                'n_chains': 1,
                'other_props': [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
            },
        },
        'Glycerophosphoglycerophosphoglycerols': {
            'Diacylglycerophosphoglycerophosphodiradylglycerols': {
                'lm_id_prefix': 'LMGP1201',
                'class_abbrev': 'CL',
                'fa_mod': '',
                'formula' : {
                    'C': lambda c: c + 9,
                    'H': lambda c, u: 2 * (c + 7 - u),
                    'N': 0,
                    'O': 17,
                    'S': 0,
                    'P': 2,
                },
                'ionization' : 'neg',
                'n_chains': 4,
                'other_props': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
            },
        },
    },
    'Sphingolipids': {
        'Ceramides': {
            'N-acylsphingosines (ceramides)': {
                'lm_id_prefix': 'LMSP0201',
                'class_abbrev': 'Cer',
                'fa_mod': 'd',
                'formula' : {
                    'C': lambda c: c,
                    'H': lambda c, u: 2 * c + 1 - 2 * u,
                    'N': 1,
                    'O': 3,
                    'S': 0,
                    'P': 0,
                },
                'ionization' : 'both',
                'n_chains': 2,
                'other_props': [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0]
            },
        },
        'Phosphosphingolipids': {
            'Ceramide phosphocholines (sphingomyelins)': {
                'lm_id_prefix': 'LMSP0301',
                'class_abbrev': 'SM',
                'fa_mod': 'd',
                'formula' : {
                    'C': lambda c: c + 5,
                    'H': lambda c, u: 2 * c + 13 - 2 * u,
                    'N': 2,
                    'O': 6,
                    'S': 0,
                    'P': 1,
                },
                'ionization' : 'pos',
                'n_chains': 2,
                'other_props': [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0]
            },
        },
    },
    'Sterol Lipids': {
        'Sterols': {
            'Sterol esters': {
                'lm_id_prefix': 'LMST0102',
                'class_abbrev': 'CE',
                'fa_mod': '',
                'formula' : {
                    'C': lambda c: c + 27,
                    'H': lambda c, u: 2 * c + 44 - 2 * u,
                    'N': 0,
                    'O': 2,
                    'S': 0,
                    'P': 0,
                },
                'ionization' : 'pos',
                'n_chains': 1,
                'other_props': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
            },
        },
    },
}


def iterate_all_lipid_classifications():
    """
    generator function that iterates through all of the entries in _LMAPS_CLASSIFICATION and yields individual lipid
    info as well as the corresponding classification info

    Yields
    ------
    class_info : tuple(str)
        lipid classification info (category, class, subclass)
    lipid_info : dict(...)
        lipid information (formula, ionization, acyl chain count)
    """
    for lcategory in LMAPS_CLASSIFICATION:
        for lclass in LMAPS_CLASSIFICATION[lcategory]:
            for lsubclass in LMAPS_CLASSIFICATION[lcategory][lclass]:
                data = LMAPS_CLASSIFICATION[lcategory][lclass][lsubclass]
                if type(data) is dict:
                    data2 = [data]
                elif type(data) is list:
                    data2 = data
                for lipid_info in data2:
                    class_info = (lcategory, lclass, lsubclass)
                    yield class_info, lipid_info
